version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-Archive-List-20250223.154059
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-app-archive-list-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - __SOURCE__:/input/
      - __SOURCE__:/output/