version: "3"
services:
  app:
    image: pudding/docker-app:docker-app-Archive-List-Index-20250223.175902
    tty: true
    command: node /app/index.js "/input/__INPUT__"
    user: "${DOCKER_UID}:${DOCKER_GID}"  # 這一行是關鍵
    environment:
      - CONTAINER_NAME=docker-app-archive-list-index-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - __SOURCE__:/input/
      - __SOURCE__:/output/